language: android
android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

script:
   - ./gradlew build connectedCheck
